In [145]:
import numpy as np 
import pandas as pd 
import torch
import base64

In [139]:
df = pd.read_excel("cache_df.xlsx")
df = df.iloc[:10]

In [147]:
# df['feature_vector'] = df['feature_vector'].astype(str)

In [148]:
df.head()

Unnamed: 0.1  Unnamed: 0                           Record Audio Name  \
0             0           0  audio_beb45dff-f264-43c5-b051-61dab6a3b2a1   
1             1           1  audio_f86da9b5-9ed2-4153-9508-e59448e7d8bc   
2             2           2  audio_0e7cded9-1569-4202-98f8-59f88384437b   
3             3           3  audio_08bf8a53-1e31-4d82-8979-b53a14baa196   
4             4           4  audio_a3b474a9-3b8e-4533-aa95-0cda51f1395d   

   Content  Pronun  Fluency                                     feature_vector  
0       18      11       25  9kUxP7DPZj4K67u/1Fm3PaSv8z5Rrrm+X4OWPsT3Ub+4qp...  
1       70      53       64  qiguP1zL8D1OM96/mJZIPyrYfz8ko1e+ZSDEPkZgUr+AKC...  
2       54      40       51  VvMwPwefkj4/nru/Mh8WPiorAz/Cory+M/yUPnRlUr8Au+...  
3       28      14       36  tPo1P3iagj4mpc2/pSsTP5CaSD/mVIW+KkacPqL5a7+6T/...  
4       16      11       25  LAIxP7YNnT6wGby/QPc5Pv2QCD8KFru+C7CTPrTKVb/YTA...

In [149]:
df.shape

(10, 7)

### Load the feature vectors corresponding to the primary keys (feature vectors are stored in MongoDB)

In [165]:
!pip install "pymongo[srv]"==3.11

     ---------------------------------------- 0.0/771.7 kB ? eta -:--:--
      --------------------------------------- 10.2/771.7 kB ? eta -:--:--
      --------------------------------------- 10.2/771.7 kB ? eta -:--:--
      ------------------------------------ 20.5/771.7 kB 165.2 kB/s eta 0:00:05
     - ----------------------------------- 41.0/771.7 kB 245.8 kB/s eta 0:00:03
     ---- ------------------------------- 102.4/771.7 kB 492.8 kB/s eta 0:00:02
     -------------------- ----------------- 409.6/771.7 kB 1.8 MB/s eta 0:00:01
     -------------------------------------- 771.7/771.7 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
   ---------------------------------------- 0.0/188.4 kB ? eta -:--:--
   --------------------------------------- 188.4/188.4 kB 11.1 MB/s eta 0:00:00
  Created wheel for pymongo: filename=pymongo-3.11.0-cp311-cp311-win_amd64.whl size=379704 sha256=fc4595c6f72ff419c2933bde1619

In [174]:
from pymongo import MongoClient

# MongoDB connection URI
uri = "mongodb+srv://bartwalkartikey1:strongandcapable@cluster0.nhigta4.mongodb.net/?appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri)

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(f"Connection failed: {e}")

# Access your specific database
mongo_db = client.Speech_Feature_Vectors

# Print collection names to verify
print("Collections in Speech_Feature_Vectors database:")
print(mongo_db.list_collection_names())

Pinged your deployment. You successfully connected to MongoDB!
Collections in Speech_Feature_Vectors database:
['main_collection']


In [167]:
client

MongoClient(host=['ac-ogfvysq-shard-00-00.nhigta4.mongodb.net:27017', 'ac-ogfvysq-shard-00-02.nhigta4.mongodb.net:27017', 'ac-ogfvysq-shard-00-01.nhigta4.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, appname='Cluster0', authsource='admin', replicaset='atlas-4duzij-shard-0', ssl=True)

In [169]:
mongo_db = client.Speech_Feature_Vectors

In [170]:
mongo_db

Database(MongoClient(host=['ac-ogfvysq-shard-00-00.nhigta4.mongodb.net:27017', 'ac-ogfvysq-shard-00-02.nhigta4.mongodb.net:27017', 'ac-ogfvysq-shard-00-01.nhigta4.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, appname='Cluster0', authsource='admin', replicaset='atlas-4duzij-shard-0', ssl=True), 'Speech_Feature_Vectors')

In [172]:
mongo_db.list_collection_names()

['main_collection']

In [173]:
mongo_db.main_collection.insert(
    {"name" : "kartikey"}
)

C:\Users\maste\AppData\Local\Temp\ipykernel_7672\773180336.py:1: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
  mongo_db.main_collection.insert(


ObjectId('66810b0ac1c2d6f6e4de2add')

In [150]:
# x = df["feature_vector"]

In [151]:
# x

0    9kUxP7DPZj4K67u/1Fm3PaSv8z5Rrrm+X4OWPsT3Ub+4qp...
1    qiguP1zL8D1OM96/mJZIPyrYfz8ko1e+ZSDEPkZgUr+AKC...
2    VvMwPwefkj4/nru/Mh8WPiorAz/Cory+M/yUPnRlUr8Au+...
3    tPo1P3iagj4mpc2/pSsTP5CaSD/mVIW+KkacPqL5a7+6T/...
4    LAIxP7YNnT6wGby/QPc5Pv2QCD8KFru+C7CTPrTKVb/YTA...
5    jPIwP4zWlj4jv7u/ZHAiPt8MBT9PSry+poGUPtpdU79Ac/...
6    /hQxP0W1nz6WXLy/AMVHPjKXCj/nG7q+kEqTPsR7V7/wEB...
7    /PowP79cmz4k+ru/pKcyPr57Bz8sh7u+oOyTPhb4VL8UOg...
8    aCwxP4a3dz7OrLu/2GXQPXDB9z7BO7u+noCWPoZcUb+4o6...
9    XAQxPyp5nT6gIry/dO07PvPaCD9R9bq+maCTPq4FVr+E8w...
Name: feature_vector, dtype: object

In [156]:
# def ascii_to_numpy(string_repr):
#     print(type(string_repr))
#     return np.frombuffer(base64.binascii.a2b_base64(string_repr.encode("ascii"))) 

In [161]:
# x = np.empty((0,))

In [164]:
# for row in df["feature_vector"]:
#     print(len(row))
#     print(type(row))
#     vector = ascii_to_numpy(row)

32767
<class 'str'>
<class 'str'>


Error: Incorrect padding

In [ ]:
# x = x.to

In [134]:
# random_array.shape

(32, 32)

In [135]:
# import pandas as pd
# import numpy as np

# # Example DataFrame
# data = {
#     'feature_vector': [
#         np.array([1, 2, 3]),
#         np.array([4, 5, 6]),
#         np.array([7, 8, 9])
#     ]
# }

# df = pd.DataFrame(data)

In [136]:
for row in df["feature_vector"]:
    print(type(row))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [137]:
# def parse_and_reshape(x):
#     # Remove unnecessary characters
#     x = x.replace('[', '').replace(']', '').replace(',', '')
#     # Split into individual numbers and convert to float
#     numbers = [float(num) for num in x.split()]
#     # Convert list to numpy array and reshape
#     return np.array(numbers).reshape((1, 1937, 512))

# # Apply the function to each element in 'feature_vector'
# df['feature_vector'] = df['feature_vector'].apply(parse_and_reshape)

# # Verify the dtype of the column
# print(df['feature_vector'].dtype)

# # Print the DataFrame to check the results
# print(df)

# # Print the DataFrame to check the results
# for row in df["feature_vector"]:
#     print(type(row))

ValueError: could not convert string to float: '...'

In [126]:
# df['feature_vector'] = df['feature_vector'].apply(np.array)

# # Alternatively, use np.asarray() for the same effect
# # df['feature_vector'] = df['feature_vector'].apply(np.asarray)
# # Verify the dtype of the column
# print(df['feature_vector'].dtype)

# # Print the DataFrame to check the results
# for row in df["feature_vector"]:
#     print(type(row))

object
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [102]:
# import base64
# import numpy as np

# for row in x:
#     row = np.frombuffer(base64.binascii.a2b_base64(row.encode("ascii"))) 
    
# # WOAH, GOTTA FIX THIS

Error: Incorrect padding

In [84]:
# x = x.apply(lambda x: np.array(eval(x)))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<string>, line 1)

In [66]:
# for row in x:
#     print(type(row))

# # WOAH, GOTTA FIX THIS

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [67]:
x_np = x.to_numpy()

In [68]:
# x_tensors = [torch.tensor(row, dtype=torch.float32) for row in x]

# # Verify each element is a tensor
# for i, tensor in enumerate(y_tensors):
#     print(f"Row {i}: {tensor}, Type: {type(tensor)}")

TypeError: new(): invalid data type 'str'

In [27]:
y = df[["Content" , "Pronun" , "Fluency"]]

In [28]:
y

Content  Pronun  Fluency
0       18      11       25
1       70      53       64
2       54      40       51
3       28      14       36
4       16      11       25
5       48      37       34
6       52      35       53
7       78      62       74
8       90      73       81
9       90      77       74

In [29]:
y_np = y.to_numpy()

In [30]:
y_np

array([[18, 11, 25],
       [70, 53, 64],
       [54, 40, 51],
       [28, 14, 36],
       [16, 11, 25],
       [48, 37, 34],
       [52, 35, 53],
       [78, 62, 74],
       [90, 73, 81],
       [90, 77, 74]], dtype=int64)

In [46]:
y_tensors = [torch.tensor(row, dtype=torch.float32) for row in y_np]

# Verify each element is a tensor
for i, tensor in enumerate(y_tensors):
    print(f"Row {i}: {tensor}, Type: {type(tensor)}")

Row 0: tensor([18., 11., 25.]), Type: <class 'torch.Tensor'>
Row 1: tensor([70., 53., 64.]), Type: <class 'torch.Tensor'>
Row 2: tensor([54., 40., 51.]), Type: <class 'torch.Tensor'>
Row 3: tensor([28., 14., 36.]), Type: <class 'torch.Tensor'>
Row 4: tensor([16., 11., 25.]), Type: <class 'torch.Tensor'>
Row 5: tensor([48., 37., 34.]), Type: <class 'torch.Tensor'>
Row 6: tensor([52., 35., 53.]), Type: <class 'torch.Tensor'>
Row 7: tensor([78., 62., 74.]), Type: <class 'torch.Tensor'>
Row 8: tensor([90., 73., 81.]), Type: <class 'torch.Tensor'>
Row 9: tensor([90., 77., 74.]), Type: <class 'torch.Tensor'>


In [44]:
y_tensors

[tensor([18., 11., 25.]),
 tensor([70., 53., 64.]),
 tensor([54., 40., 51.]),
 tensor([28., 14., 36.]),
 tensor([16., 11., 25.]),
 tensor([48., 37., 34.]),
 tensor([52., 35., 53.]),
 tensor([78., 62., 74.]),
 tensor([90., 73., 81.]),
 tensor([90., 77., 74.])]

In [47]:
y = y_tensors

In [51]:
print(x)
print(len(x))

0    tensor([[[ 0.6925,  0.2254, -1.4681,  ..., -0....
1    tensor([[[ 0.6803,  0.1176, -1.7359,  ..., -0....
2    tensor([[[ 0.6912,  0.2864, -1.4658,  ..., -0....
3    tensor([[[ 0.7109,  0.2551, -1.6066,  ..., -0....
4    tensor([[[ 0.6914,  0.3067, -1.4695,  ..., -0....
5    tensor([[[ 0.6912,  0.2946, -1.4668,  ..., -0....
6    tensor([[[ 0.6917,  0.3119, -1.4716,  ..., -0....
7    tensor([[[ 0.6913,  0.3034, -1.4686,  ..., -0....
8    tensor([[[ 0.6921,  0.2419, -1.4662,  ..., -0....
9    tensor([[[ 0.6915,  0.3076, -1.4698,  ..., -0....
Name: feature_vector, dtype: object
10


In [52]:
print(y)
print(len(y))

[tensor([18., 11., 25.]), tensor([70., 53., 64.]), tensor([54., 40., 51.]), tensor([28., 14., 36.]), tensor([16., 11., 25.]), tensor([48., 37., 34.]), tensor([52., 35., 53.]), tensor([78., 62., 74.]), tensor([90., 73., 81.]), tensor([90., 77., 74.])]
10


In [4]:
from transformers import Wav2Vec2FeatureExtractor, Wav2Vec2Model

model_name = "facebook/wav2vec2-large-xlsr-53"
feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(model_name)
wav2vec2_model = Wav2Vec2Model.from_pretrained(model_name)

Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-large-xlsr-53 and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [5]:
model

Wav2Vec2Model(
  (feature_extractor): Wav2Vec2FeatureEncoder(
    (conv_layers): ModuleList(
      (0): Wav2Vec2LayerNormConvLayer(
        (conv): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (1-4): 4 x Wav2Vec2LayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(3,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (5-6): 2 x Wav2Vec2LayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(2,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
    )
  )
  (feature_projection): Wav2Vec2FeatureProjection(
    (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (projection): Linear(in_features=512, out_features=1024, bias=True)
    (dropout)

In [9]:
import tensorflow as tf

def custom_activation(x):
    return 10 * tf.nn.sigmoid(x)
    
class Wav2Vec2ForScoring(tf.keras.Model):
    def __init__(self , wav2vec2_model , num_classes):
        super().__init__()
        self.wav2vec2_model = wav2vec2_model
        self.fc = tf.keras.layers.Dense(num_classes , activation = custom_activation)
    
    def call(self , inputs):
        # pass the inputs to the bert model
        x = self.wav2vec3_model(inputs)
        # the model outputs: last_hidden state and pooler_output
        # these are the logits with respect to bert
        x = x[1]
        # since we only wanted the pooler_output
        return self.fc(x)


In [14]:
scoring_model = Wav2Vec2ForScoring(wav2vec2_model , num_classes = 3)

scoring_model.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate = 1e-5),
    loss = tf.keras.losses.MeanSquaredError(),
    metrics = ['accuracy']
)

In [13]:
scoring_model

<Wav2Vec2ForScoring name=wav2_vec2_for_scoring_1, built=False>

In [53]:
history = scoring_model.fit(
    (x , y),
    epochs = 3
)

ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 10, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3
